---
title: "House Property Sales"
author: "Oscar Monroy"
date: "6/16/2022"
output: pdf_document
---

# Bringing in the Data

```{r}
hps <- read.csv("ma_lga_12345.csv")
head(hps, 10)
summary(hps) # Everything seems to be in order
sum(duplicated(hps)) # No duplicate data
hps$saledate <- as.Date(hps$saledate, format = "%d/%m/%Y")
hps$bedrooms <- as.factor(hps$bedrooms)
head(hps, 10)
```

# Plotting the Current Quarterly Values

```{r}
library(ggplot2)
ggplot(data = hps, aes(x = saledate, y = MA, group = bedrooms, color = bedrooms)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Moving Average of Median Price") +
  xlab("Year") + 
  ggtitle("Quarterly Average Median Price of Property Per Year by # of Bedrooms")

ggplot(data = hps, aes(x = saledate, y = MA, group = bedrooms, color = bedrooms)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_grid(~ type) +
  ylab("Moving Average of Median Price") +
  xlab("Year") + 
  ggtitle("Q. Average Median Price of Property Type Per Year by # of Bedrooms")

ggplot(data = hps, aes(x = bedrooms, y = MA, color = bedrooms)) +
  geom_boxplot() +
  facet_grid(~ type) +
  ylab("Moving Average of Median Price") +
  ggtitle("Boxplot of Moving Avg. of Median Price by # of Bedrooms")
```

# Implementing the Time Series Function for Property Types

```{r}
library(dplyr)
unit_1br <- hps %>% filter(bedrooms == 1, type == "unit")
unit_1br <- ts(unit_1br[,2], start = c(2007, 4), frequency = 4)

unit_2br <- hps %>% filter(bedrooms == 2, type == "unit")
unit_2br <- ts(unit_2br[,2], start = c(2007, 2), frequency = 4)

unit_3br <- hps %>% filter(bedrooms == 3, type == "unit")
unit_3br <- ts(unit_3br[,2], start = c(2007, 3), frequency = 4)

house_2br <- hps %>% filter(bedrooms == 2, type == "house")
house_2br <- ts(house_2br[,2], start = c(2007, 3), frequency = 4)

house_3br <- hps %>% filter(bedrooms == 3, type == "house")
house_3br <- ts(house_3br[,2], start = c(2007, 1), frequency = 4)

house_4br <- hps %>% filter(bedrooms == 4, type == "house")
house_4br <- ts(house_4br[,2], start = c(2007, 1), frequency = 4)

house_5br <- hps %>% filter(bedrooms == 5, type == "house")
house_5br <- ts(house_5br[,2], start = c(2007, 3), frequency = 4)
```

# Forecasting Models

```{r}
# install.packages("forecast")
# install.packages("quantmod")
library(forecast)
arima_u1 <- auto.arima(unit_1br)
summary(arima_u1)
u1_f <- forecast(arima_u1, 13)
u1_f

arima_u2 <- auto.arima(unit_2br)
summary(arima_u2)
u2_f <- forecast(arima_u2, 12)
u2_f

arima_u3 <- auto.arima(unit_3br)
summary(arima_u3)
u3_f <- forecast(arima_u3, 13)
u3_f

arima_h2 <- auto.arima(house_2br)
summary(arima_h2)
h2_f <- forecast(arima_h2, 13)
h2_f

arima_h3 <- auto.arima(house_3br)
summary(arima_h3)
h3_f <- forecast(arima_h3, 13)
h3_f

arima_h4 <- auto.arima(house_4br)
summary(arima_h4)
h4_f <- forecast(arima_h4, 13)
h4_f

arima_h5 <- auto.arima(house_5br)
summary(arima_h5)
h5_f <- forecast(arima_h5, 13)
h5_f
```

# Graphing out the Forecast Models

```{r}
plot(unit_1br, xlim = c(2007, 2023), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 1 BR Unit Until Q4 2022")
lines(u1_f$mean, col = "green")

plot(unit_2br, xlim = c(2007, 2023), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 2 BR Unit Until Q4 2022")
lines(u2_f$mean, col = "green")

plot(unit_3br, xlim = c(2007, 2023), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 3 BR Unit Until Q4 2022")
lines(u3_f$mean, col = "green")

plot(house_2br, xlim = c(2007, 2023), 
     ylim = c(400000, 550000), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 2 BR House Until Q4 2022")
lines(h2_f$mean, col = "green")

plot(house_3br, xlim = c(2007, 2023),
     ylim = c(400000, 700000), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 3 BR House Until Q4 2022")
lines(h3_f$mean, col = "green")

plot(house_4br, xlim = c(2007, 2023), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 4 BR House Until Q4 2022")
lines(h4_f$mean, col = "green")

plot(house_5br, xlim = c(2007, 2023), ylab = "Moving Average of Median Price",
     main = "Forecast of Median Price of 5 BR House Until Q4 2022")
lines(h5_f$mean, col = "green")
```



